model_name: meta-llama/Meta-Llama-3-8B-Instruct
prompt_path: prompts/costar_cot_1shot.txt
save_dir: models
wandb_project_name: AIMO

# Text Environment
text_env_tools: []
text_env_max_turns: 1

# Training
epochs: 10
train_batch_size: 64
train_mini_batch_size: 1
val_batch_size: 10
gradient_accumulation_steps: 32
generation_max_new_tokens: 500
precision: bf16

learning_rate: 0.00001
warnup_steps: 100